const INITIAL_EMPLOYEES = [
  {
    "id": "190",
    "no": "13",
    "nombre": "EMPLEADO 1",
    "empresa": "AHA",
    "area": "ADMINISTRATIVA",
    "depto": "MARKETING",
    "puesto": "CONTENT MANAGER",
    "lugar": "CORPORATIVO",
    "ingreso": "2025-08-11",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 370.43,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "DESCONTAR 1 DIA / VALIDADO CON SU JEFE DIRECTO",
    "dias_trabajados": 14,
    "faltas": 1,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "171",
    "no": "14",
    "nombre": "EMPLEADO 2",
    "empresa": "BYRMAX",
    "area": "TECNICA",
    "depto": "PRODUCCION",
    "puesto": "TOPOGRAFO",
    "lugar": "MAZATLAN",
    "ingreso": "2020-05-22",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 781.01,
    "asimilados": 0.0,
    "gasolina": 2000.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "108",
    "no": "18",
    "nombre": "EMPLEADO 3",
    "empresa": "CPI/ ASIMIL",
    "area": "TECNICA",
    "depto": "INGENIERIA",
    "puesto": "PROYECTISTA URBANIZACIÓN",
    "lugar": "CORPORATIVO",
    "ingreso": "2013-07-01",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 0.0,
    "asimilados": 28121.84,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "TIENE UN ADEUDO DE $35,745.37 CORRESPONDIENTE A UN PRESTAMO POR $125,000 (05 DE SEP 2025) QUE SE ABONARA EN 5 PAGOS MENSUALES DE $6,244.18 EMPEZANDO El 15 ABRIL A AGOSTO 2026.",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "081",
    "no": "19",
    "nombre": "EMPLEADO 4",
    "empresa": "CPI",
    "area": "TECNICA",
    "depto": "GESTORIA",
    "puesto": "AUXILIAR DE GESTORIA",
    "lugar": "CORPORATIVO",
    "ingreso": "2021-11-18",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 441.02,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 3000.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "TEMP_10",
    "no": "23",
    "nombre": "EMPLEADO 5",
    "empresa": "FACTURA",
    "area": "COMERCIAL",
    "depto": "PROSPECCIÓN DIGITAL",
    "puesto": "GERENTE DE VENTAS DIGITALES",
    "lugar": "CORPORATIVO",
    "ingreso": "2016-06-01",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 0.0,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 17451.3,
    "deuda_carro": 0.0,
    "observaciones": "OK, PAGO CON FACTURA/SUELDO UNA VEZ AL MES LOS DIAS 15",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "8",
    "no": "60",
    "nombre": "EMPLEADO 6",
    "empresa": "CPI-ASIMIL",
    "area": "TECNICA",
    "depto": "COMPRAS",
    "puesto": "GERENTE DE COMPRAS",
    "lugar": "CORPORATIVO",
    "ingreso": "2017-08-22",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 0.0,
    "asimilados": 19031.15,
    "gasolina": 0.0,
    "socio": 19864.899999999998,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 6104.0,
    "observaciones": "OK, SE PAGA SUELDO BRUTO MENSUAL, SE PAGA LOS 17 DE CADA MES",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "56",
    "no": "65",
    "nombre": "EMPLEADO 7",
    "empresa": "AHA-ASIMIL",
    "area": "ADMINISTRATIVA",
    "depto": "DIRECCION",
    "puesto": "DIRECTOR DE MERCADOTECNIA",
    "lugar": "CORPORATIVO",
    "ingreso": "2002-08-14",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 0.0,
    "asimilados": 108274.13,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 35000.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK, SE PAGA SUELDO BRUTO MENSUAL, SE PAGA LOS 17 DE CADA MES",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "TEMP_13",
    "no": "68",
    "nombre": "EMPLEADO 8",
    "empresa": "CPI",
    "area": "ADMINISTRATIVA",
    "depto": "CONTABILIDAD",
    "puesto": "CONTADOR",
    "lugar": "CORPORATIVO",
    "ingreso": "2023-08-01",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 686.26,
    "asimilados": 0.0,
    "gasolina": 2035.74,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "PRESTAMO DE 20,000.00, A PAGAR CON EL FONDO DE AHORRO CUANDO SE ENTREGUE",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "141",
    "no": "1",
    "nombre": "EMPLEADO 9",
    "empresa": "CPI",
    "area": "TECNICA",
    "depto": "CONTABILIDAD",
    "puesto": "CONTADOR",
    "lugar": "CORPORATIVO",
    "ingreso": "2024-06-03",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 387.34,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "TEMP_15",
    "no": "71",
    "nombre": "EMPLEADO 10",
    "empresa": "CPI",
    "area": "JURIDICO",
    "depto": "JURIDICO",
    "puesto": "ABOGADA",
    "lugar": "CORPORATIVO",
    "ingreso": "2023-02-01",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 1042.3,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "269",
    "no": "109",
    "nombre": "EMPLEADO 11",
    "empresa": "LASO",
    "area": "TECNICA",
    "depto": "PRODUCCION",
    "puesto": "SUPERVISOR DE OBRA",
    "lugar": "MAZATLAN",
    "ingreso": "2025-02-24",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 587.94,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "127",
    "no": "110",
    "nombre": "EMPLEADO 12",
    "empresa": "CPI",
    "area": "OPERATIVA",
    "depto": "OPERACIONES",
    "puesto": "IMAGEN URBANA",
    "lugar": "CULIACAN",
    "ingreso": "2016-01-25",
    "baja": null,
    "fondo_ahorro_activo": true,
    "salario_diario": 819.33,
    "asimilados": 0.0,
    "gasolina": 1000.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "128",
    "no": "111",
    "nombre": "EMPLEADO 13",
    "empresa": "AHA",
    "area": "COMERCIAL",
    "depto": "PROSPECCIÓN DIGITAL",
    "puesto": "PROSPECCIÓN DIGITAL",
    "lugar": "CORPORATIVO",
    "ingreso": "2021-05-03",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 315.04,
    "asimilados": 0.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "OK",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "026",
    "no": "112",
    "nombre": "EMPLEADO 14",
    "empresa": "BYRMAX",
    "area": "TECNICA",
    "depto": "DIRECCION",
    "puesto": "GERENCIA GRAL",
    "lugar": "CORPORATIVO",
    "ingreso": "2011-08-27",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 315.04,
    "asimilados": 49115.19,
    "gasolina": 0.0,
    "socio": 49115.19,
    "efectivo": 38000.0,
    "facturado": 150000.0,
    "deuda_carro": 0.0,
    "observaciones": "COMISIONES QUE SE PAGA EL ULTIMO DIA DE CADA MES,",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  },
  {
    "id": "TEMP_20",
    "no": "138",
    "nombre": "EMPLEADO 15",
    "empresa": "CPI-ASIMIL",
    "area": "OPERATIVA",
    "depto": "OPERACIONES",
    "puesto": "IMAGEN URBANA",
    "lugar": "CULIACAN",
    "ingreso": "2026-02-24",
    "baja": null,
    "fondo_ahorro_activo": false,
    "salario_diario": 0.0,
    "asimilados": 16200.0,
    "gasolina": 0.0,
    "socio": 0.0,
    "efectivo": 0.0,
    "facturado": 0.0,
    "deuda_carro": 0.0,
    "observaciones": "SE PAGA LOS 17 DE CADA MES",
    "dias_trabajados": 15,
    "faltas": 0,
    "vacaciones": 0,
    "retardos": 0,
    "descuento_adicional": 0.0
  }
];